// Liste complète des 114 sourates avec noms arabes et français
export const SOURATES_LIST = [
  {n:1,ph:"fatiha",ar:"الفاتحة",fr:"L'Ouverture",v:7},
  {n:2,ph:"baqara",ar:"البقرة",fr:"La Vache",v:286},
  {n:3,ph:"imran",ar:"آل عمران",fr:"La Famille d'Imran",v:200},
  {n:4,ph:"nissa",ar:"النساء",fr:"Les Femmes",v:176},
  {n:5,ph:"maida",ar:"المائدة",fr:"La Table Servie",v:120},
  {n:6,ph:"anam",ar:"الأنعام",fr:"Les Bestiaux",v:165},
  {n:7,ph:"araf",ar:"الأعراف",fr:"Les Murailles",v:206},
  {n:8,ph:"anfal",ar:"الأنفال",fr:"Le Butin",v:75},
  {n:9,ph:"tawba",ar:"التوبة",fr:"Le Repentir",v:129},
  {n:10,ph:"yunus",ar:"يونس",fr:"Jonas",v:109},
  {n:11,ph:"hud",ar:"هود",fr:"Houd",v:123},
  {n:12,ph:"yusuf",ar:"يوسف",fr:"Joseph",v:111},
  {n:13,ph:"rad",ar:"الرعد",fr:"Le Tonnerre",v:43},
  {n:14,ph:"ibrahim",ar:"إبراهيم",fr:"Abraham",v:52},
  {n:15,ph:"hijr",ar:"الحجر",fr:"Al-Hijr",v:99},
  {n:16,ph:"nahl",ar:"النحل",fr:"Les Abeilles",v:128},
  {n:17,ph:"isra",ar:"الإسراء",fr:"Le Voyage Nocturne",v:111},
  {n:18,ph:"kahf",ar:"الكهف",fr:"La Caverne",v:110},
  {n:19,ph:"maryam",ar:"مريم",fr:"Marie",v:98},
  {n:20,ph:"taha",ar:"طه",fr:"Tâ-Hâ",v:135},
  {n:21,ph:"anbiya",ar:"الأنبياء",fr:"Les Prophètes",v:112},
  {n:22,ph:"hajj",ar:"الحج",fr:"Le Pèlerinage",v:78},
  {n:23,ph:"muminun",ar:"المؤمنون",fr:"Les Croyants",v:118},
  {n:24,ph:"nur",ar:"النور",fr:"La Lumière",v:64},
  {n:25,ph:"furqan",ar:"الفرقان",fr:"Le Discernement",v:77},
  {n:26,ph:"shuara",ar:"الشعراء",fr:"Les Poètes",v:227},
  {n:27,ph:"naml",ar:"النمل",fr:"Les Fourmis",v:93},
  {n:28,ph:"qasas",ar:"القصص",fr:"Le Récit",v:88},
  {n:29,ph:"ankabut",ar:"العنكبوت",fr:"L'Araignée",v:69},
  {n:30,ph:"rum",ar:"الروم",fr:"Les Romains",v:60},
  {n:31,ph:"luqman",ar:"لقمان",fr:"Luqmân",v:34},
  {n:32,ph:"sajda",ar:"السجدة",fr:"La Prosternation",v:30},
  {n:33,ph:"ahzab",ar:"الأحزاب",fr:"Les Coalisés",v:73},
  {n:34,ph:"saba",ar:"سبأ",fr:"Saba",v:54},
  {n:35,ph:"fatir",ar:"فاطر",fr:"Le Créateur",v:45},
  {n:36,ph:"yasin",ar:"يس",fr:"Yâ-Sîn",v:83},
  {n:37,ph:"saffat",ar:"الصافات",fr:"Ceux en Rangs",v:182},
  {n:38,ph:"sad",ar:"ص",fr:"Sâd",v:88},
  {n:39,ph:"zumar",ar:"الزمر",fr:"Les Groupes",v:75},
  {n:40,ph:"ghafir",ar:"غافر",fr:"Le Pardonneur",v:85},
  {n:41,ph:"fussilat",ar:"فصلت",fr:"Explicitée",v:54},
  {n:42,ph:"shura",ar:"الشورى",fr:"La Consultation",v:53},
  {n:43,ph:"zukhruf",ar:"الزخرف",fr:"L'Ornement",v:89},
  {n:44,ph:"dukhan",ar:"الدخان",fr:"La Fumée",v:59},
  {n:45,ph:"jathiya",ar:"الجاثية",fr:"L'Agenouillée",v:37},
  {n:46,ph:"ahqaf",ar:"الأحقاف",fr:"Les Dunes",v:35},
  {n:47,ph:"muhammad",ar:"محمد",fr:"Muhammad",v:38},
  {n:48,ph:"fath",ar:"الفتح",fr:"La Victoire",v:29},
  {n:49,ph:"hujurat",ar:"الحجرات",fr:"Les Appartements",v:18},
  {n:50,ph:"qaf",ar:"ق",fr:"Qâf",v:45},
  {n:51,ph:"dhariyat",ar:"الذاريات",fr:"Les Vents",v:60},
  {n:52,ph:"tur",ar:"الطور",fr:"Le Mont Sinaï",v:49},
  {n:53,ph:"najm",ar:"النجم",fr:"L'Étoile",v:62},
  {n:54,ph:"qamar",ar:"القمر",fr:"La Lune",v:55},
  {n:55,ph:"rahman",ar:"الرحمن",fr:"Le Miséricordieux",v:78},
  {n:56,ph:"waqia",ar:"الواقعة",fr:"L'Évènement",v:96},
  {n:57,ph:"hadid",ar:"الحديد",fr:"Le Fer",v:29},
  {n:58,ph:"mujadila",ar:"المجادلة",fr:"La Discussion",v:22},
  {n:59,ph:"hashr",ar:"الحشر",fr:"L'Exode",v:24},
  {n:60,ph:"mumtahina",ar:"الممتحنة",fr:"L'Éprouvée",v:13},
  {n:61,ph:"saff",ar:"الصف",fr:"Les Rangs",v:14},
  {n:62,ph:"jumua",ar:"الجمعة",fr:"Le Vendredi",v:11},
  {n:63,ph:"munafiqun",ar:"المنافقون",fr:"Les Hypocrites",v:11},
  {n:64,ph:"taghabun",ar:"التغابن",fr:"La Spoliation",v:18},
  {n:65,ph:"talaq",ar:"الطلاق",fr:"Le Divorce",v:12},
  {n:66,ph:"tahrim",ar:"التحريم",fr:"L'Interdiction",v:12},
  {n:67,ph:"mulk",ar:"الملك",fr:"La Royauté",v:30},
  {n:68,ph:"qalam",ar:"القلم",fr:"La Plume",v:52},
  {n:69,ph:"haqqa",ar:"الحاقة",fr:"L'Inévitable",v:52},
  {n:70,ph:"maarij",ar:"المعارج",fr:"Les Degrés",v:44},
  {n:71,ph:"nuh",ar:"نوح",fr:"Noé",v:28},
  {n:72,ph:"jinn",ar:"الجن",fr:"Les Djinns",v:28},
  {n:73,ph:"muzzammil",ar:"المزمل",fr:"L'Enveloppé",v:20},
  {n:74,ph:"muddaththir",ar:"المدثر",fr:"Le Revêtu",v:56},
  {n:75,ph:"qiyama",ar:"القيامة",fr:"La Résurrection",v:40},
  {n:76,ph:"insan",ar:"الإنسان",fr:"L'Homme",v:31},
  {n:77,ph:"mursalat",ar:"المرسلات",fr:"Les Envoyés",v:50},
  {n:78,ph:"naba",ar:"النبأ",fr:"La Nouvelle",v:40},
  {n:79,ph:"naziat",ar:"النازعات",fr:"Les Arracheurs",v:46},
  {n:80,ph:"abasa",ar:"عبس",fr:"Il a Froncé",v:42},
  {n:81,ph:"takwir",ar:"التكوير",fr:"L'Enroulement",v:29},
  {n:82,ph:"infitar",ar:"الانفطار",fr:"La Rupture",v:19},
  {n:83,ph:"mutaffifin",ar:"المطففين",fr:"Les Fraudeurs",v:36},
  {n:84,ph:"inshiqaq",ar:"الانشقاق",fr:"La Fissure",v:25},
  {n:85,ph:"buruj",ar:"البروج",fr:"Les Constellations",v:22},
  {n:86,ph:"tariq",ar:"الطارق",fr:"L'Astre Nocturne",v:17},
  {n:87,ph:"ala",ar:"الأعلى",fr:"Le Très Haut",v:19},
  {n:88,ph:"ghashiya",ar:"الغاشية",fr:"L'Enveloppante",v:26},
  {n:89,ph:"fajr",ar:"الفجر",fr:"L'Aurore",v:30},
  {n:90,ph:"balad",ar:"البلد",fr:"La Cité",v:20},
  {n:91,ph:"shams",ar:"الشمس",fr:"Le Soleil",v:15},
  {n:92,ph:"layl",ar:"الليل",fr:"La Nuit",v:21},
  {n:93,ph:"duha",ar:"الضحى",fr:"La Matinée",v:11},
  {n:94,ph:"sharh",ar:"الشرح",fr:"L'Ouverture du Cœur",v:8},
  {n:95,ph:"tin",ar:"التين",fr:"Le Figuier",v:8},
  {n:96,ph:"alaq",ar:"العلق",fr:"Le Caillot",v:19},
  {n:97,ph:"qadr",ar:"القدر",fr:"La Destinée",v:5},
  {n:98,ph:"bayyina",ar:"البينة",fr:"La Preuve",v:8},
  {n:99,ph:"zalzala",ar:"الزلزلة",fr:"Le Séisme",v:8},
  {n:100,ph:"adiyat",ar:"العاديات",fr:"Les Coursiers",v:11},
  {n:101,ph:"qaria",ar:"القارعة",fr:"La Fracassante",v:11},
  {n:102,ph:"takathur",ar:"التكاثر",fr:"La Surenchère",v:8},
  {n:103,ph:"asr",ar:"العصر",fr:"L'Époque",v:3},
  {n:104,ph:"humaza",ar:"الهمزة",fr:"Le Médisant",v:9},
  {n:105,ph:"fil",ar:"الفيل",fr:"L'Éléphant",v:5},
  {n:106,ph:"quraysh",ar:"قريش",fr:"Quraysh",v:4},
  {n:107,ph:"maun",ar:"الماعون",fr:"L'Ustensile",v:7},
  {n:108,ph:"kawthar",ar:"الكوثر",fr:"L'Abondance",v:3},
  {n:109,ph:"kafirun",ar:"الكافرون",fr:"Les Mécréants",v:6},
  {n:110,ph:"nasr",ar:"النصر",fr:"Le Secours",v:3},
  {n:111,ph:"masad",ar:"المسد",fr:"Les Fibres",v:5},
  {n:112,ph:"ikhlas",ar:"الإخلاص",fr:"La Pureté",v:4},
  {n:113,ph:"falaq",ar:"الفلق",fr:"L'Aube",v:5},
  {n:114,ph:"nas",ar:"الناس",fr:"Les Hommes",v:6},
]
